### ISSUE TITLE
Default page template

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Staff#10]
Again, this might be another training question :) Is there a way to make a news/spotlight item take up the full with of the content, instead of having the "events" column there? Or is there a way to pick and choose which news/spotlight items I would like to have that far right column visible? I'm thinking that on some stories we will want to just have the story, but if there is an event that would pertain to the story have the option of adding that column back in with the events?

**Comment by joelworsham** [comment]
This issue was moved to JacksonCollege/Primary-Theme#26
