### ISSUE TITLE
Staff question

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Staff#12]
Sorry, another training question, not really about functionality :)

I love this staff section! I added myself as an employee then created a marketing and communications page just to see how it would look, but was unable to figure out how to add the staff info on to the page? Or I guess this is just a general question on how to add a content type to a page? I have a similar issue with the FAQ area...I did an FAQ question but didn't really know how to add it to a page to be able to view it? I'm dumb... :) Would there be a specific page template I would need to select?

**Comment by joelworsham** [comment]
Right, so when creating a page, select the page template "Archive - Staff" and it will display the staff directory.

**Comment by banksashleym** [comment]
Awesome, thanks! I did have a question about the look of the contact that was in a previous issue...and we can address this later when we are out of phase II. I don't want to confuse the functionality portion with the design portion.

Would it be possible to create an additional contact "band" that would appear after the main content that would include department/program contact info? So each college department and each program would have their main contact info along the left side and then list the members of the department on the right portion of the band? and could we include a side navigation link for "contact" that, when clicked, travels down the page to the contact section?

I created a page a while back that was part of the academics accounting design that had a gray band at the bottom with the look of the contact info at http://jackson-college-website.webflow.io/accounting.

Thanks!

**Comment by joelworsham** [comment]
Ah okay. So somewhere within the Program we setup which Staff Department belongs to it, and then that band is auto-populated by staff that exist inside of it?

I also notice that one staff member in that band is prominent, and then there's a list of others that exist in that department. Is this a distinction at the staff level? Or does this change per program?

**Comment by banksashleym** [comment]
Yes, exactly! For the accounting example, Suzanne Keiss happens to be the faculty that is in charge of the whole department, but also a faculty member. There might be a contact person for some, but not for others. Like for the marketing department we would just list "Marketing & Communications" and then the location and not list a specific contact person on the left side, but then include all of our photos/bios along the right!

**Comment by joelworsham** [comment]
I believe we are no longer doing this
