### ISSUE TITLE
Academics degrees

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Staff#13]
I think this whole academics section looks so great!! It's very easy to navigate and add content.

on the program pages (accounting example: http://jacksoncollege.staging.wpengine.com/program/accounting/). In the top left gray box "Jackson college offers these degrees..." would there be a workaround just for the time being to have the degree buttons "Associate in applied science" link directly to a pdf instead of going to the degree page with the listing of semesters/courses? Or maybe the ability on the back end to link both to the pdf as well as to the degree page (just so I have a working example to show the committee). I won't have all of the degree info for our new pathways until about mid-February, so I will be working on those pages on the back-end and making them all live once I have the complete info for them. So for the time being we would like to just link to the pdfs that we have out there now?

**Comment by joelworsham** [comment]
This issue was moved to JacksonCollege/Academics-Management#1
