### ISSUE TITLE
Academics Pathway - major map link

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Staff#17]
Hi Joel,
I'm starting to add the academics information in to the website. When you click on a pathway and the list of degrees shows up there is a link called "major map" I'm just curious as to where I can upload the printable pdf on the dashboard? There wasn't an area on the degrees tab in the plugin - I would assume it would be here since there is a spot where you can add what type of degree it is?

For now, the the major map link will link to the same pdf that you did an override for on the degrees pages. And when we have all of our pathway information built in, this major map link will link and the "Printable Degree map" button on the degree page will also link to the same pdf (we planned on formatting a nice looking pdf that is in printable format.)

http://jacksoncollege.staging.wpengine.com/pathway/business-computer-technology-2/

 Let me know if this doesn't make sense, I'm confusing myself just trying to explain it!

**Comment by joelworsham** [comment]
I wasn't sure what would be presented with the "Major Map" button, so it was left empty for now. I can add a place to upload the PDF. I will also have the "PDF replacement" override and take priority of this button when present.

**Comment by joelworsham** [comment]
This issue was moved to JacksonCollege/Academics-Management#7
