### ISSUE TITLE
Academics - order of degrees on Program pages

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Staff#18]
Is there a way I can manually decide what order the degrees show up on the program pages? For example, on the accounting program page, we normally list the Associate degree first and then the certificate, but it is automatically putting the certificate at the top of the list?

http://jacksoncollege.staging.wpengine.com/program/accounting-2/?preview=true

UPDATE: As I'm adding more degrees, it looks as if they are in alpha order, but they order Z-A...if we could re-order it so that they are alphabetical by A-Z I think it should fix the problem altoghether. when I'm on an individual pathway page they are in reverse order, so changing that around should fix it.

Thanks!

**Comment by joelworsham** [comment]
Are you sure you do not want a manual ordering mechanism? Ordering A-Z definitely is an easy fix, but if you need more control let me know.

**Comment by banksashleym** [comment]
I would like the ability to manually order the nav links if possible. Thank you!

**Comment by joelworsham** [comment]
This issue was moved to JacksonCollege/Academics-Management#5
