### ISSUE TITLE
Programs page jobs box

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Staff#20]
Would it be possible in the "job opportunities" box to remove the automatic bulleted list and make it a normal paragraph? There are some jobs where we list the opportunities more as a paragraph so we can explain them a little better.

Thanks!

http://jacksoncollege.staging.wpengine.com/program/energy-systems/?preview=true&preview_id=3566&preview_nonce=e529e058f0

**Comment by brashrebel** [comment]
Sure. Perhaps the option for both should be available?

**Comment by banksashleym** [comment]
That would be perfect, thanks!

**Comment by joelworsham** [comment]
This issue was moved to JacksonCollege/Academics-Management#6
