### ISSUE TITLE
Program pages ability to hide/disable boxes

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Staff#21]
Would there be a way to disable or hide all/some of the boxes on the program pages? For instance, we don't necessarily offer an English degree, it's more of a transfer program - and there is so much you can do with an english degree that we don't really have concrete pay/career information, but I would still like the "Jackson college offers... box". When I leave text areas blank the boxes still show up. just without any content.

Thanks!

http://jacksoncollege.staging.wpengine.com/program/english/?preview=true&preview_id=3580&preview_nonce=abac9710f6

**Comment by brashrebel** [comment]
Good to know. We'll be sure to only show these elements if data for them exists.

**Comment by banksashleym** [comment]
Great!

**Comment by joelworsham** [comment]
This issue was moved to JacksonCollege/Academics-Management#4
