### ISSUE TITLE
News Banner Image functionality

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Staff#3]
When a visitor click on a news item story and goes to the landing page - could we make the banner image across all of these pages be a static banner image? When I was uploading, the photos worked really well in the more rectangular space on the home page, but on the landing page the photo didn't seem to translate as well..I'm thinking we will use that same featured image from the home page as a photo in the body of the story instead of in the banner.

**Comment by joelworsham** [comment]
This issue was moved to JacksonCollege/Primary-Theme#20
